<html>
    <body>
        <main>
            <h1> Построение бизнеса поэтапно. </h1>
            <p> Цель добиться мотивации от посетителей сайта:</p>
            <ol>
                <li> Примеры мотивации персонала</li>
<li> Примеры стимулирования</li>
<li> Основные группы методов мотивации.</li>
<li> Нематериальная мотивация</li>
<li> Формы мотивации персонала</li>
<li> Соционика</li>
            </ol>
            <img src="https://static10.tgstat.ru/channels/_0/d8/d8a65988bbf766d22b1a6910a25fab86.jpg"
  width="200" height="150">          
        </main>
        <footer>
            <a href="...">Подробное видео о мотивации подготовления бизнеса поэтапно:</a>
        <video>
  <source src="https://youtu.be/d6xbr0IQ87I">
</video>
<video width="400" height="300" controls="controls" poster="video/duel.jpg">
   <source src="https://youtu.be/d6xbr0IQ87I" codecs="https://youtu.be/d6xbr0IQ87I">
   <source src="https://youtu.be/d6xbr0IQ87I"  codecs="https://youtu.be/d6xbr0IQ87I, https://youtu.be/d6xbr0IQ87I"'>
   <source src="https://youtu.be/d6xbr0IQ87I"  codecs="https://youtu.be/d6xbr0IQ87I, https://youtu.be/d6xbr0IQ87I"'>
   <source src=""  codecs="https://youtu.be/d6xbr0IQ87I, mp4a.40.2"'>
   <source src=""  codecs="https://youtu.be/d6xbr0IQ87I, mp4a.40.2"'>
   <source src="https://youtu.be/d6xbr0IQ87I"  codecs="vp8, vorbis"'>
    <a href="https://youtu.be/d6xbr0IQ87I">Скачайте видео</a>.
  </video>
       <main>
        <p>  Я со своим высшим профессиональным образованием маркетолога и  увлекаюсь программированием , и создал специально для вас сайт , в котором  вы можете посмотреть все мотивации подготовления бизнеса , но самое важное , что я провожу экскурсии виртуально . Надеюсь , что вам будет интересно!  </p>
</main>
         <footer>
    <p> тел. +89988779966  эл. почта ErikHalikov2008@yandex.ru</p></footer>
        </footer>
    </body>
</html>
body {
    font-family: sans-serif;
}
body {
    font-family: sans-serif;
    background-color:rgb(150, 159, 200) ;
    background: 
url("https://mars.algoritmika.org/uploads/2021/01/fish2_0_1610653588.svg")no-repeat 50% 40%,
url("https://mars.algoritmika.org/uploads/2021/01/fish1_0_1610653588.svg")no-repeat 70% 90%,
url("https://mars.algoritmika.org/uploads/2021/01/coral_0_1610653588.svg")no-repeat 90% 70%,
}

h1 {
    background-color: indigo;
    color: white;
    padding: 10px;
}

img {
    height: 200px;
}

p, ul {
    font-size: 20px;
}

footer {
    margin: 20px;
}

footer a{
    text-decoration: none;
    color: white;
    font-size: 30px;
    border: 1px solid indigo;
    background-color: indigo;
    padding: 5px;
    border-radius: 10px;
}

